global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-servers'
    static_configs:
      - targets:
        - '192.168.56.61:9100'  # app1
        - '192.168.56.62:9100'  # app2
        labels:
          group: 'application-servers'
